export const Assets = Object.freeze({
  menu: { background: 'assets/backgrounds/menu/main_menu_background.png', logo: 'assets/ui/menu/game_logo.png' },
  hub: {
    background: 'assets/backgrounds/hub/HB01.png', growthBackground: 'assets/backgrounds/hub/HB14.png',
    shelf: 'assets/ui/hub/HB02.png', arrow: 'assets/ui/hub/HB03.png', category: 'assets/ui/hub/HB08.png',
    primaryButton: 'assets/ui/hub/HB05.png', secondaryButton: 'assets/ui/hub/HB06.png', detailPanel: 'assets/ui/hub/HB07.png',
    locked: 'assets/ui/hub/HB09.png', settings: 'assets/ui/hub/HB10.png', ferrymanCard: 'assets/ui/hub/HB11.png',
    growthNode: 'assets/ui/hub/HB15.png', back: 'assets/ui/hub/HB16.png',
    infoPanel: 'assets/ui/hub/characters/info_panel_9slice.png',
    stageEntry: 'assets/ui/hub/stages/stage_entry_panel.png', ferryPrimaryButton: 'assets/ui/hub/buttons/ferry_primary_button.png',
  },
  resources: { copper: 'assets/ui/resources/RS01.png', soulFlame: 'assets/ui/resources/RS02.png' },
  ferrymen: {
    feichuan: { portrait: 'assets/characters/CH01.png', avatar: 'assets/characters/AV01.png' },
    moyu: { portrait: 'assets/characters/CH02.png', avatar: 'assets/characters/AV02.png' },
    qinglan: { portrait: 'assets/characters/CH03.png', avatar: 'assets/characters/AV03.png' },
  },
  prologue: {
    backgrounds: {
      ferry: 'assets/backgrounds/prologue/BA07.png',
      road: 'assets/backgrounds/prologue/BA08.png',
      shallows: 'assets/backgrounds/prologue/BA09.png',
    },
    child: {
      normal: 'assets/souls/prologue/GH-P01.png',
      hesitant: 'assets/souls/prologue/GH-P02.png',
      released: 'assets/souls/prologue/GH-P03.png',
    },
    woodenBoat: 'assets/story/prologue/PR-P01.png',
  },
  cards: { frame: 'assets/cards/frames/UI01.png', back: 'assets/cards/frames/UI02.png', feichuanFrame: 'assets/cards/feichuan/FCF01.png' },
  piles: { UC01: 'assets/ui/card/UC01.png', UC02: 'assets/ui/card/UC02.png', UC03: 'assets/ui/card/UC03.png' },
  battle: { intent: 'assets/ui/battle/UI03.png' },
  traits: { TR01: 'assets/ui/traits/TR01.png' },
  run: {
    background: 'assets/backgrounds/run/BA05.png',
    reward: { normal: 'assets/ui/run/reward/RW01-A.png', hover: 'assets/ui/run/reward/RW01-B.png', selected: 'assets/ui/run/reward/RW01-C.png', title: 'assets/ui/run/reward/RW02.png' },
    progress: { pending: 'assets/ui/run/progress/RP01-A.png', current: 'assets/ui/run/progress/RP01-B.png', complete: 'assets/ui/run/progress/RP01-C.png', pathPending: 'assets/ui/run/progress/RP02-A.png', pathComplete: 'assets/ui/run/progress/RP02-B.png' },
    buttons: { normal: 'assets/ui/run/buttons/RB01-A.png', hover: 'assets/ui/run/buttons/RB01-B.png', pressed: 'assets/ui/run/buttons/RB01-C.png' },
    result: { ferry: 'assets/ui/run/result/RR01.png', panel: 'assets/ui/run/result/RR02.png' },
  },
  icons: { IC01: 'assets/ui/icons/IC01.png', IC02: 'assets/ui/icons/IC02.png', IC03: 'assets/ui/icons/IC03.png', IC04: 'assets/ui/icons/IC04.png', IC05: 'assets/ui/icons/IC05.png', IC06: 'assets/ui/icons/IC06.png', IC07: 'assets/ui/icons/IC07.png' },
  effects: { soul_flame: 'assets/effects/soul/FX01.png', release_glow: 'assets/effects/soul/FX02.png' },
  souls: { unresolved: 'assets/souls/GH01.png', released: 'assets/souls/GH02.png', prologueChild: { normal: 'assets/souls/prologue/GH-P01.png', hesitant: 'assets/souls/prologue/GH-P02.png', released: 'assets/souls/prologue/GH-P03.png' } },
  results: { success: 'assets/ui/results/RT01.png', failure: 'assets/ui/results/RT02.png' },
});
